/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistematelefonico;

/**
 *
 * @author said
 */
public class FramePrincipal extends javax.swing.JFrame {
    Tiempo cronometro = new Tiempo();
    private boolean super_control = true;
    /**
     * Creates new form NewJFrame
     */
    
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phone6 = new javax.swing.JLabel();
        phone1 = new javax.swing.JLabel();
        phone4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        phone8 = new javax.swing.JLabel();
        phone5 = new javax.swing.JLabel();
        phone3 = new javax.swing.JLabel();
        phone7 = new javax.swing.JLabel();
        phone2 = new javax.swing.JLabel();
        lperdidas = new javax.swing.JLabel();
        txtCronometro = new javax.swing.JLabel();
        llamadas = new javax.swing.JLabel();
        txtBloqueadas = new javax.swing.JLabel();
        txtAtendidas = new javax.swing.JLabel();
        txtOcupadas = new javax.swing.JLabel();
        txtDisponibles = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phone6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistematelefonico/disponible.png"))); // NOI18N
        phone6.setText("#6");
        getContentPane().add(phone6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 311, -1, -1));

        phone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistematelefonico/disponible.png"))); // NOI18N
        phone1.setText("#1");
        getContentPane().add(phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 103, -1, -1));

        phone4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistematelefonico/disponible.png"))); // NOI18N
        phone4.setText("#4");
        getContentPane().add(phone4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 210, -1, -1));

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane2.setViewportView(txtLog);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 395, 710, 127));

        phone8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistematelefonico/disponible.png"))); // NOI18N
        phone8.setText("#8");
        getContentPane().add(phone8, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 311, -1, -1));

        phone5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistematelefonico/disponible.png"))); // NOI18N
        phone5.setText("#5");
        getContentPane().add(phone5, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 210, -1, -1));

        phone3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistematelefonico/disponible.png"))); // NOI18N
        phone3.setText("#3");
        getContentPane().add(phone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 103, -1, -1));

        phone7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistematelefonico/disponible.png"))); // NOI18N
        phone7.setText("#7");
        getContentPane().add(phone7, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 311, -1, -1));

        phone2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistematelefonico/disponible.png"))); // NOI18N
        phone2.setText("#2");
        getContentPane().add(phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 103, -1, -1));

        lperdidas.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lperdidas.setText("0: Llamadas bloqueadas");
        getContentPane().add(lperdidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 20, -1, -1));

        txtCronometro.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        txtCronometro.setText("00:00");
        getContentPane().add(txtCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        llamadas.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        llamadas.setText("0: Total llamadas");
        getContentPane().add(llamadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 6, -1, 43));

        txtBloqueadas.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        txtBloqueadas.setText("0: Llamadas perdidas");
        getContentPane().add(txtBloqueadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 55, -1, -1));

        txtAtendidas.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        txtAtendidas.setText("0: Llamadas atendidas");
        getContentPane().add(txtAtendidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 55, -1, -1));

        txtOcupadas.setText(": Lineas disponibles");
        getContentPane().add(txtOcupadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        txtDisponibles.setText(": Lineas ocupadas");
        getContentPane().add(txtDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistematelefonico/server.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jButton1.setText("DETENER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:cronometro
        cronometro.Detener();
        super_control = false;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new FramePrincipal().setVisible(true);
            }
        });
        
    }
    
    public void randomEstado(){
        cronometro.Contar();
        
        
        Telefono telefonos[] = new Telefono[8];
        
        telefonos[0] = new Telefono(false, null, (1), phone1);
        telefonos[1] = new Telefono(false, null, (2), phone2);
        telefonos[2] = new Telefono(false, null, (3), phone3);
        telefonos[3] = new Telefono(false, null, (4), phone4);
        telefonos[4] = new Telefono(false, null, (5), phone5);
        telefonos[5] = new Telefono(false, null, (6), phone6);
        telefonos[6] = new Telefono(false, null, (7), phone7);
        telefonos[7] = new Telefono(false, null, (8), phone8);
        
        int idTelOrigen = -1, idTelDestino = -1;
        int perdidas = 0, llamadas = 0, bloqueadas = 0, atendidas = 0;
        int lineas = 3;
        int control = 0;
        
        while(super_control){
            txtCronometro.setText(""+cronometro.getSegundos()+"sgs");
            repaint();
            control = (int) (Math.random() * 2)+1;
            idTelOrigen = (int) (Math.random() * 7)+1;
            if(control == 1 && lineas > 0){
                pausa((int) (Math.random() * 4000)+300);
                llamadas++;updateLlamadas(llamadas);
                while(idTelOrigen == -1 || telefonos[idTelOrigen].isOcupado() ){ idTelOrigen = (int) (Math.random() * 7) ; bloqueadas++; txtBloqueadas.setText(""+bloqueadas+": Llamadas bloqueadas");}
                telefonos[idTelOrigen].setEstado(true);
                while(idTelDestino == -1 || telefonos[idTelDestino].isOcupado() ){ idTelDestino = (int) (Math.random() * 7) ; perdidas++; llamadas++; updateLlamadas(llamadas); updatePerdidas(perdidas); }
                telefonos[idTelDestino].setEstado(true);
                atendidas++;
                
                txtAtendidas.setText(""+ atendidas +": Llamadas atendidas");

                telefonos[idTelOrigen].getIndicador().setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistematelefonico/ocupado.png")));
                telefonos[idTelOrigen].setConexion(telefonos[idTelDestino]);
                telefonos[idTelDestino].getIndicador().setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistematelefonico/ocupado.png")));
                telefonos[idTelDestino].setConexion(telefonos[idTelOrigen]);

                lineas--;
                printLog("Telefono "+(idTelOrigen+1)+" -> Telefono "+(idTelDestino+1)); //invierto el estado);
            } else if (control == 2){
                if(idTelOrigen >= 0 && telefonos[idTelOrigen].isOcupado()){
                    liberarLinea(telefonos[idTelOrigen]);
                    lineas++;
                }
                
            }
            updateLineas(lineas);
            printLog("Lineas disponibles: "+lineas);
        }
    }
    
    
    public void updateLlamadas(int c){
        llamadas.setText(c+": Total de llamadas");
    }
    
    public void updatePerdidas(int c){
        lperdidas.setText(c+": Llamadas perdidas");
    }
    
    public void liberarLinea(Telefono telefono){
        telefono.getIndicador().setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistematelefonico/disponible.png")));
        telefono.getConexion().getIndicador().setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistematelefonico/disponible.png")));
        telefono.setEstado(false);
        telefono.getConexion().setEstado(false);
        printLog("Llamada terminada.");
    }
    
    public void printLog(String text){
        String log ="";
        log += ""+txtLog.getText()+"";
        log +=""+text+"\n";
        txtLog.setText(log);
    }
    
    public void updateLineas(int t){
        txtOcupadas.setText(""+t+": Lineas disponibles");
        txtDisponibles.setText(""+(3-t)+": Lineas ocupadas");
    }
    
    public void pausa(int tiempo){
        try{
            Thread.sleep(tiempo);
            repaint();
        }catch(InterruptedException e){System.out.println(e.getMessage());}
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JLabel llamadas;
    private javax.swing.JLabel lperdidas;
    private static javax.swing.JLabel phone1;
    private static javax.swing.JLabel phone2;
    private javax.swing.JLabel phone3;
    private javax.swing.JLabel phone4;
    private javax.swing.JLabel phone5;
    private javax.swing.JLabel phone6;
    private javax.swing.JLabel phone7;
    private javax.swing.JLabel phone8;
    private javax.swing.JLabel txtAtendidas;
    private javax.swing.JLabel txtBloqueadas;
    private static javax.swing.JLabel txtCronometro;
    private javax.swing.JLabel txtDisponibles;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JLabel txtOcupadas;
    // End of variables declaration//GEN-END:variables
}
